import {
  pgTable,
  uuid,
  text,
  integer,
  real,
  boolean,
  timestamp,
  jsonb,
} from "drizzle-orm/pg-core";

export const config = pgTable("config", {
  id: uuid("id").defaultRandom().primaryKey(),
  riskTolerance: integer("risk_tolerance").notNull().default(5),
  maxSlippageBps: integer("max_slippage_bps").notNull().default(100),
  maxMovesPerDay: integer("max_moves_per_day").notNull().default(5),
  circuitBreakerPct: real("circuit_breaker_pct").notNull().default(10),
  gasBudgetUsdPerDay: real("gas_budget_usd_per_day").notNull().default(20),
  rebalanceThresholdPct: real("rebalance_threshold_pct").notNull().default(2),
  isPaused: boolean("is_paused").notNull().default(false),
  pauseReason: text("pause_reason"),
  telegramChatId: text("telegram_chat_id"),
  evmAddress: text("evm_address"),
  solanaAddress: text("solana_address"),
  bittensorAddress: text("bittensor_address"),
  encryptedEvmKey: text("encrypted_evm_key"),
  encryptedSolanaKey: text("encrypted_solana_key"),
  encryptedBittensorKey: text("encrypted_bittensor_key"),
  onboardedAt: timestamp("onboarded_at"),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

export const positions = pgTable("positions", {
  id: uuid("id").defaultRandom().primaryKey(),
  chain: text("chain").notNull(),
  protocol: text("protocol").notNull(),
  pool: text("pool").notNull(),
  symbol: text("symbol").notNull(),
  amountUsd: real("amount_usd").notNull(),
  amountNative: text("amount_native").notNull(),
  tokenAddress: text("token_address"),
  entryApy: real("entry_apy").notNull(),
  currentApy: real("current_apy"),
  status: text("status").notNull().default("active"),
  entryTxHash: text("entry_tx_hash"),
  exitTxHash: text("exit_tx_hash"),
  enteredAt: timestamp("entered_at").notNull(),
  exitedAt: timestamp("exited_at"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const opportunities = pgTable("opportunities", {
  id: uuid("id").defaultRandom().primaryKey(),
  llamaPoolId: text("llama_pool_id").notNull().unique(),
  chain: text("chain").notNull(),
  protocol: text("protocol").notNull(),
  symbol: text("symbol").notNull(),
  tvlUsd: real("tvl_usd").notNull(),
  apy: real("apy").notNull(),
  apyBase: real("apy_base"),
  apyReward: real("apy_reward"),
  apyMean30d: real("apy_mean_30d"),
  stablecoin: boolean("stablecoin").notNull().default(false),
  ilRisk: text("il_risk"),
  mu: real("mu"),
  sigma: real("sigma"),
  riskScore: real("risk_score"),
  vibeScore: real("vibe_score"),
  executable: boolean("executable").notNull().default(false),
  scannedAt: timestamp("scanned_at").defaultNow().notNull(),
});

export const transactions = pgTable("transactions", {
  id: uuid("id").defaultRandom().primaryKey(),
  positionId: uuid("position_id").references(() => positions.id),
  chain: text("chain").notNull(),
  txHash: text("tx_hash"),
  type: text("type").notNull(),
  fromToken: text("from_token"),
  toToken: text("to_token"),
  amountUsd: real("amount_usd"),
  gasCostUsd: real("gas_cost_usd"),
  slippageBps: integer("slippage_bps"),
  status: text("status").notNull().default("pending"),
  errorMessage: text("error_message"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const portfolioSnapshots = pgTable("portfolio_snapshots", {
  id: uuid("id").defaultRandom().primaryKey(),
  timestamp: timestamp("timestamp").defaultNow().notNull(),
  totalValueUsd: real("total_value_usd").notNull(),
  totalYieldEarnedUsd: real("total_yield_earned_usd").notNull().default(0),
  totalGasSpentUsd: real("total_gas_spent_usd").notNull().default(0),
  netApyCurrent: real("net_apy_current"),
  positionCount: integer("position_count").notNull().default(0),
  highWaterMarkUsd: real("high_water_mark_usd").notNull().default(0),
  drawdownPct: real("drawdown_pct").notNull().default(0),
  chainBreakdown: jsonb("chain_breakdown"),
});

export const auditLog = pgTable("audit_log", {
  id: uuid("id").defaultRandom().primaryKey(),
  timestamp: timestamp("timestamp").defaultNow().notNull(),
  agent: text("agent").notNull(),
  action: text("action").notNull(),
  summary: text("summary").notNull(),
  details: jsonb("details"),
  claudeTokensUsed: integer("claude_tokens_used"),
});
